// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgidR2_IsxvgPodGWhEySPL039t39DIA',
    appId: '1:61137632110:web:448da9f64b950faa485f7f',
    messagingSenderId: '61137632110',
    projectId: 'cuisine-7fba1',
    authDomain: 'cuisine-7fba1.firebaseapp.com',
    storageBucket: 'cuisine-7fba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWOzt7wziOkin-KI0piBs7uMPTzy0y8pw',
    appId: '1:61137632110:android:1c410f96107fe075485f7f',
    messagingSenderId: '61137632110',
    projectId: 'cuisine-7fba1',
    storageBucket: 'cuisine-7fba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7pDNapQ_0ywHFx4HEWCCXr_9tLrKQeTg',
    appId: '1:61137632110:ios:6b29d28491a6667e485f7f',
    messagingSenderId: '61137632110',
    projectId: 'cuisine-7fba1',
    storageBucket: 'cuisine-7fba1.appspot.com',
    iosClientId: '61137632110-n4ds9bcm5eu6pbtr4l8k0qaqh3nosep8.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7pDNapQ_0ywHFx4HEWCCXr_9tLrKQeTg',
    appId: '1:61137632110:ios:6b29d28491a6667e485f7f',
    messagingSenderId: '61137632110',
    projectId: 'cuisine-7fba1',
    storageBucket: 'cuisine-7fba1.appspot.com',
    iosClientId: '61137632110-n4ds9bcm5eu6pbtr4l8k0qaqh3nosep8.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp',
  );
}
